### ISSUE TITLE
add Workbook.save() method

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#110]

**Comment by bklaas** [comment]
This is the only direct reference I can find anywhere for save...is it accurate to say that the current released version of xlwings (0.3) cannot save changes at all?

There must be something incredibly hard about saving a spreadsheet, especially xlsx, because looking across the breadth of spreadsheet parsing libraries in Python, Perl, and Ruby, they all seem to have this limitation with xlsx: they either can't save changes or cannot edit an already-in-place xlsx file.

**Comment by fzumstein** [comment]
`save` hasn't been implemented, yes. Again - there's a good chance it'll make it into 0.3.1. The thing that is still missing I feel is the possibility to control the `working directory` from Excel (apart from the Mac version playing funny last time I tried). Same as for your other comment though: If you are on Windows, use this workaround: `wb.xl_workbook.SaveAs(r"C:\...\test.xlsx")`
