### ISSUE TITLE
Add Sheet.used_range property

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#112]

**Comment by bklaas** [comment]
I would have immediate use for a used_range method. Case in point, I deal with spreadsheets that have sparse tabular data. That is, not every cell in the relevant portion of the spreadsheet can be expected to have values in them. As a result, the horizontal and vertical methods are not reliable because they grab the first N cells before hitting a blank cell, then stop.

The workaround method I'm doing for this involves looking downward in the first column for an <end> tag (which luckily is present, only because of our own conventions). I can effectively find the last used row in the spreadsheet this way, but it's by far the biggest bottleneck in the code I'm writing.

Word of warning: I've accessed the COM object's UsedRange field before in VBA, and I've never felt completely confident it can be trusted.

**Comment by fzumstein** [comment]
There's a good chance it'll be in 0.3.1 -- in the meantime, you can use the following workaround (assuming you are on Windows): `Sheet('Sheet1').xl_sheet.UsedRange.GetAddress()`, to get the address of the bottom right cell, for example. You're word of warning is correct - that's something you have to keep in mind...

**Comment by kudai** [comment]
Most of these approaches are pretty inefficient.

I found an excel formula that computes it - so I'm writing it to an unused cell in Excel and reading back the value. The difference for me was from 12 seconds to less than 0.1 seconds!
The formula is "=MATCH(REPT(\"z\",255), [excel range]"
