### ISSUE TITLE
bug if PYTHONPATH contains multiple directories

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#258]
If PYTHONPATH contains multiple directories separated by ";" the RunCommand is not correct.

        RunCommand = "python -c ""import sys; sys.path.append(r'" & PYTHONPATH & "'); " & Command & """ "

can be replaced by

        RunCommand = "python -c ""import sys; sys.path.extend(r'" & PYTHONPATH & ".split(";")'); " & Command & """ "

**Comment by sdementen** [comment]
Hello Felix, I did a PR for both issues 258 and 257. I am not familiar yet with PRs, did I do that correctly ? Do I need to do an extra step ?

**Comment by fzumstein** [comment]
Regarding the PRs, there's nothing really wrong, but I still have the following inputs:

- Name PRs according to what they to, i.e `Added app property` rather than `proposal for issue #253`
- Same goes for the underlying branch, better to name it `app-property` than something like `patch1` - but I think you've already done that in the more recent PRs
- If possible and if it makes sense, add a unit test

**Comment by fzumstein** [comment]
Just noticed now that this has to be fixed for Mac and OptimizedConnection also

**Comment by fzumstein** [comment]
Fixed by 93cd8f6d830ac0d047b86d828d91f9d5c8566ecd

**Comment by xkeecs** [comment]
did a google search and found this solution. so in the new version we can separate multiple python path by ";". I think it's better to change the docs: http://docs.xlwings.org/en/stable/addin.html here to make the description of PYTHONPATH consistent with UDF_MODULES.
