### ISSUE TITLE
include pywin32 as dependency in setup.py?

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#298]
It's available now as wheel since quite some time on pypi (pypiwin32)

**Comment by Juanlu001** [comment]
This would definitely simplify installation problems, also because the pypiwin32 wheels use a hack in the .pth file which helps locate the correct DLL.

**Comment by fzumstein** [comment]
Umm but the pypi version doesn't seem to be official. It's still on v 219 and 220 has been out since the beginning of the year.

**Comment by Juanlu001** [comment]
It's never been official, Glyph updated it because he didn't get any response from pywin32 maintainer, see this thread:

https://sourceforge.net/p/pywin32/bugs/669/

Many people are moving away from pywin32 because it's full of problems and doesn't play well with the existing Python packaging stack, see also

https://twistedmatrix.com/trac/ticket/7477

**Comment by fzumstein** [comment]
Closing this for now... conda package works flawlessly....
