### ISSUE TITLE
Parameter from python to vba

### ISSUE THREAD

**Issue by sethor** [ZoomerAnalytics/xlwings#361]
Hi! I would like to ask if there is a way to pass a parameter from python (i.e. a python function called with RunPython) to the caller VBA module? I don't want to modify anything in the worksheet, just pass back the parameter. Thank you very much for your help!

**Comment by fzumstein** [comment]
No, not directly since I remember that you're not able to use the decorator syntax. Maybe calling a VBA macro from Python would be an option. While this hasn't been natively implemented in xlwings yet, it should be simple to call via the underlying libraries, see: https://github.com/ZoomerAnalytics/xlwings/issues/134

**Comment by sethor** [comment]
Thank you, my problem originates from the fact that I can't use macro-enabled excel files, so calling a macro from outside is not an option either, unfortunately. Thank you for the help anyway!

**Comment by fzumstein** [comment]
I think you should be able to call macros in an add-in, i.e. the place where I guess you keep the xlwings VBA module.

**Comment by sethor** [comment]
Yes, I've tried and I really can call add-ins, but my major problem remains: the Workbook.caller() functions throws an AttributeError when I call it from a cell directly with = myfunction()
Could you help me with that?

**Comment by sethor** [comment]
And of course thank you very much for you help, you answered this issue, so I'm gonna open another one for this problem.
