### ISSUE TITLE
Pulling data without any formatting from excel

### ISSUE THREAD

**Issue by sethor** [ZoomerAnalytics/xlwings#434]
Hi,
Could you tell me if there is a way to pull data from Excel without any formatting? I would need the data to be exactly in the same form as I see it in the Excel table and with xlwings 0.6.4 (we have updated to this version, so we don't have access to v0.7.0's range.options facility). My primary problem is the number --> float conversion - I have to work with an enormous amount of data, the remove of that couple thousand .0 -s would effect the speed of my program.
I tried to set the input column's format to string, but that doesn't seem to work.
Is there any way around this problem?
Thank you very much for your help inadvance!

**Comment by fzumstein** [comment]
Numbers are stored in Excel internally always as float, so that's why a no-conversion means that they arrive as floats in Excel.

If it's only about reading in data, you could have a look also at `xlrd` or `openpyxl`, they might be more efficient. You can still process them further with xlwings after you have read them into Python with one of the other libraries.

**Comment by sethor** [comment]
Thank you, I wrote a little something to convert every float back to int and it does not seem to make the program that slow.
