### ISSUE TITLE
Zombie process using xlwings

### ISSUE THREAD

**Issue by coolpix77** [ZoomerAnalytics/xlwings#479]
Hi,

This post refer to my previous post in stackoverflow : http://stackoverflow.com/questions/37548171/zombie-process-using-xlwings

> When I use xlwings to automate stuff in excel, I still have EXCEL zoombie process running even if I quit the application (with wb.Application(wb).quit()).
> 
> Thus, when I try to re open my excel file that bugs. I have to manually kill the excel application.
> 
> edit : I use the xlwings 0.7.0

**Comment by fzumstein** [comment]
And here my answer from SO for reference:

The issue is that `wb` is a global reference to your workbook which still exists even after executing the quit command. Excel sees that it is being referenced (through COM) and thus refuses to shut down properly.

For now, you can manually clean up your workbook object after quitting: `del wb`. In the next major release of xlwings, we'll also provide a new `Workbook.kill()` command that will get around this issue.
