### ISSUE TITLE
0.9.0 fails to start with Python 3.5 on Windows

### ISSUE THREAD

**Issue by aberres** [ZoomerAnalytics/xlwings#533]
With vanilla python as well as with WinPython 3.5 I a m running into an input error complaining about missing _ctypes_test.
0.7.2 on Windows as well as 0.9.0 on Mac are working fine.

```
Traceback (most recent call last):
  File "c:\users\b\local\p3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\b\local\p3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\b\local\p3\Scripts\xlwings.exe\__main__.py", line 5, in <module>
  File "c:\users\b\local\p3\lib\site-packages\xlwings\__init__.py", line 38, in <module>
    from .udfs import xlfunc as func, xlsub as sub, xlret as ret, xlarg as arg, get_udf_module, import_udfs
  File "c:\users\b\local\p3\lib\site-packages\xlwings\udfs.py", line 6, in <module>
    from _ctypes_test import func
ImportError: No module named '_ctypes_test'
```

**Comment by stonebig** [comment]
stupid question: how does excel find winpython (or the winpython we want it to use) ?

**Comment by stonebig** [comment]
ok, found.

**Comment by fzumstein** [comment]
By default it starts python by executing `python` from the command line, i.e. this works if you have a default python installation on your PATH. Since WinPython doesn't add the location to the PATH, you need to change `PYTHON_WIN` to the path where WinPython resides, see: http://docs.xlwings.org/en/stable/vba.html#settings This currently is in the VBA module.

Note that we're working on turning the VBA module into an addin that stores the settings in an external settings file, so you should in theory be able to automatically change the path in the settings upon installation of WinPython.

**Comment by stonebig** [comment]
So there's no dependancy, and it can ship on winpythonzero  ?

**Comment by stonebig** [comment]
what about the nightmare Excel 32 bit on a windows 64 ? no issue ?

**Comment by fzumstein** [comment]
the only dependency that xlwings has on windows that is not automatically installed when doing `pip install xlwings` is pywin32, but as I recall this is part of WinPython so you should have no problems.
xlwings works with all combinations of Windows/Excel/Python bitness, since its running out of process.

**Comment by stonebig** [comment]
argh, pywin32 is 8Mo big

**Comment by fzumstein** [comment]
not sure if I follow, according to this list, pywin32 is already included: https://github.com/winpython/winpython/blob/master/changelogs/WinPythonQt5-3.4.4.6.md

**Comment by stonebig** [comment]
yes, but not in the small winpythonzero.

**Comment by stonebig** [comment]
can we use xlwings with all the python  code only present in the excel sheet ?

**Comment by fzumstein** [comment]
It has been discussed before, but it's not a priority for us: https://github.com/ZoomerAnalytics/xlwings/issues/107

**Comment by stonebig** [comment]
ok.

**Comment by stonebig** [comment]
I don't perceive yet the added functionnality of anaconda "fusion" over "xlwings" alone.
