### ISSUE TITLE
Relative and Absolute cell references

### ISSUE THREAD

**Issue by vipuljain11** [ZoomerAnalytics/xlwings#603]
Please provide the feature to have Relative and Absolute cell references and fill down option.

Facing difficulty while applying the formula for the current region/set of rows

**Comment by fzumstein** [comment]
Can you please provide a sample either how you would do it in Excel/VBA or pseudo xlwings code.

**Comment by vipuljain11** [comment]
Thank you Felix for your reply. I was pretty new to the python and trying to automate some of the excel stuff. I could able to mange by the following lines... by this I could iterate through the cells to write the formula.

wb = xw.Book('C:\\Users\\temp.xlsx')
ws =wb.sheets("Dataset")
ws["AI1"].value=  "Month"
rownum= xw.apps(1).books('temp.xlsx').sheets("Dataset").range('A1').current_region.last_cell.row
colnum =xw.apps(1).books('temp.xlsx').sheets("Dataset").range('A1').current_region.last_cell.column
ws["AI1"].value=  "Month"
ws["AR1"].value=  "Count of Accounts"
i=2
for i in range(2,rownum+1):
    
    ws["AI"+str(i)].value='="M" & CHOOSE(MONTH(AC'+str(i)+'),2,3,1,2,3,1,2,3,1,2,3,1)'

**Comment by fzumstein** [comment]
Note that it's easier to loop using the `Range` object with a tuple as index pair:

```
for i in range(2, rownum + 1):
    ws.range((i, 35)).value = ...
```

However, you shouldn't do that expect for very small ranges as otherwise it gets very slow. Create arrays in python, loop there and write it back in one go: See also the `Note` under http://docs.xlwings.org/en/stable/datastructures.html#range-expanding
