### ISSUE TITLE
insert image at given cell position?

### ISSUE THREAD

**Issue by retsyo** [ZoomerAnalytics/xlwings#632]
Since I can't insert equation in excel via  Python, I think I can render euqation as a picture file then insert it in given cell. However, even when I record and replay a VBA, the inserted image is always placed at the top-left corner.

Any solution in xlwings?

Thanks

**Comment by fzumstein** [comment]
See http://docs.xlwings.org/en/stable/api.html#xlwings.main.Pictures.add, you can do something like: 

```
rng = wb.sheets[0].range("B2")
xw.pictures.add('mypic.jpg', top=rng.top, left=rng.left)
```

**Comment by asakist** [comment]
@fzumstein 
I am trying to replicate the above code but I receive error. (I guess instead of xw you mean ws, a worksheet?)
While I am running :
`ws.pictures.add('mypic.jpg')`
the excel file opens with an error 
`"An error occurred while importing this file. mypic.jpg"`
And inside the console in spyder I receive the error :
`com_error: (-2147352567, 'Exeption occured.',(0, None, None, None, 0, -2146827284), None)`
- Any ideas, please?
