### ISSUE TITLE
Read data in Accounting format

### ISSUE THREAD

**Issue by houpigtiger** [ZoomerAnalytics/xlwings#640]
[Book1.xlsx](https://github.com/ZoomerAnalytics/xlwings/files/821609/Book1.xlsx)

I've attached an example workbook. I generated the numbers using np.random.randn:
[[0.7145271196730558, -0.7610235250453997],
 [0.6804524169745054, 0.9407596136240517],
 [-0.29428893448350885, 1.4862470447957117]].  
The first column is in general format, while the second column is showing numbers in US dollars. 

The following all return the second column as Python Decimal objects which truncates the numbers:
sht.range('A1').expand().options(pd.DataFrame. index=False).value
sht.range('A1').expand().options(numbers=float).value
sht.range('A1').expand().raw_value

[['a', 'b'],
 [0.7145271196730558, Decimal('-0.761')],
 [0.6804524169745054, Decimal('0.9408')],
 [-0.29428893448350885, Decimal('1.4862')]]

However, if I use pandas to read in the sheet, 
df = pd.read_excel('Book1.xlsx', 'Sheet1')

I get the second column back as float numbers which is the result I desired:
a	b
0	0.714527	-0.761024
1	0.680452	0.940760
2	-0.294289	1.486247

**Comment by fzumstein** [comment]
This relates to #65 and is a "feature" of the underlying pywin32 package. We need to see how we can best fix this but for now you could try to work around it with 

```
sht.range('A1').expand().api.Value2
```

**Comment by houpigtiger** [comment]
Thanks. I'll use api for that.

**Comment by smetterspa** [comment]
This approach nicely transforms currency from truncated Decimal to float. But, consider a date that would otherwise be recognized as datetime.datetime using the more standard .value method. In this case, the method api.Value2 tries to convert the date to a float. I could not find an options command for turning off this date conversion using api.Value2. Does one exist? If not, what is the best approach? Thank you.
