### ISSUE TITLE
Why python+xlwings is so slow than VBA?

### ISSUE THREAD

**Issue by reaCodes** [ZoomerAnalytics/xlwings#860]
Do the same to Excel, Python+xlwings need `56 s`, but VBA only need `0.4 s`
 How to speed up Python+xlwings?

![carbon](https://user-images.githubusercontent.com/13817254/39659464-0410b83e-505b-11e8-903b-18037ded6b3e.png)
![qq 20180505115839](https://user-images.githubusercontent.com/13817254/39659495-b2847cac-505b-11e8-9201-06bb176864fc.png)
![qq 20180505115108](https://user-images.githubusercontent.com/13817254/39659496-bb33fbde-505b-11e8-8dcf-45639a436206.png)

**Comment by DougAJ4** [comment]
Create the array in Python, then write it to Excel in a single operation.
If you use Numpy that will probably be faster than the VBA code you posted, although that could also be made much faster by creating the array in VBA, and copying to the spreadsheet in a single step.

**Comment by DougAJ4** [comment]
```
@xw.func
def fillrange(rows, cols):
    stime = time.clock()
    rows = int(rows)
    cols = int(cols)
    rtna = np.zeros((rows, cols))
    for i in range(0, cols):
        for j in range(0, rows):
            rtna[j,i] = i*j 
    rtna[0,0] = time.clock() - stime
    return rtna
```

**Comment by reaCodes** [comment]
@DougAJ4 

OMG!!😲

Using this way, Python+xlwings is more faster than VBA. Why this? In my previous method, which part of the operation consumed too much time? 

Please tell me how to avoid this kind of performance error? In other words, which actions can speed up Python+xlwings?

---
![qq 20180505133152](https://user-images.githubusercontent.com/13817254/39660058-e8176f4c-5069-11e8-81fb-78f6054c68dd.png)
![qq 20180505133134](https://user-images.githubusercontent.com/13817254/39660060-ecae25e6-5069-11e8-8bb1-5d77504767de.png)
![qq 20180505133125](https://user-images.githubusercontent.com/13817254/39660062-f05e2402-5069-11e8-9cd3-8ba50c539e1d.png)

**Comment by reaCodes** [comment]
@DougAJ4 

But why I have used `screen_updating = 'False'` also can't speed up Python+xlwings?

Maybe whatever if I use `screen_update` or not, Python always create a value and then transfer it to Excel immediately.

So too many transmissions consume most of time, update screen don't consume much time. This is the reason why I can't speed up the operation by `screen_updating = 'False'`. Is that right

**Comment by fzumstein** [comment]
It's the cross application calls that are slow, see the bottom blue box here: http://docs.xlwings.org/en/stable/datastructures.html#lists

There's also a free preview about that topic ("Efficiency") on our video course: https://training.zoomeranalytics.com/p/xlwings

**Comment by rmwitt** [comment]
python and vba are both fast, if called directly from their native environment.  The issue is calling python from Excel.  Excel has the overhead of starting the interactive window (i.e. cmd prompt), load python, run the py.code, return the information to excel, and close the interactive window (ie. cmd prompt).   The time hogs are opening and closing the interactive window (i.e. cmd prompt).  It doesn't matter whether the window is displayed or hidden, the time to do all of that is the same.  

You can change the setting "RunPython: Use UDF Server" to True, see: http://docs.xlwings.org/en/stable/addin.html#global-settings which will not shut down the interpreter in between calls. Currently, you'll have the overhead only with the first call.

You can also decorate your functions with "@xw.sub" instead and then they work like UDFs (i.e. you need to import them): http://docs.xlwings.org/en/stable/udfs.html#macros

Neither one are great solutions for me.  Plus I could not get either one to work...very buggy.
